[package]
name = "bits"
version = "0.1.0"
authors = ["James Conroy-Finn <james@invetica.co.uk>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
dioxus = { version = "0.7.1", features = ["router", "fullstack"] }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "macros"], optional = true }
tokio = { version = "1", features = ["sync"], optional = true }
tracing = "0.1.41"

[features]
default = ["web", "server"]
web = ["dioxus/web"]
server = ["dioxus/server", "sqlx", "tokio"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
