[package]
name = "bits"
version = "0.1.0"
authors = ["James Conroy-Finn <james@invetica.co.uk>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.7.0", features = ["router", "fullstack"] }
axum = { version = "0.7", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"], optional = true }
url = "2.5"
reqwest = "0.12.24"

[features]
default = ["web"]
server = ["dioxus/server", "dep:axum", "dep:tokio"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
