[application]
name = "bits"
default_platform = "web"
tailwind_input = "tailwind.css"
tailwind_output = "assets/app.css"

[web.app]
title = "Bits"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[web.watcher]
reload_html = true
