[formatter.javascript]
command = "prettier"
options = ["--cache", "--write"]
includes = [
  "*.astro",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.svelte",
  "*.ts",
  "*.tsx",
  "*.yaml",
  "*.yml",
]
excludes = [
  "node_modules/**",
  "pnpm-lock.yaml",
  "resources/public/*.js"
]

[formatter.clojure]
command = "cljfmt"
options = ["fix"]
includes = ["*.clj", "*.cljc", "*.cljs", "*.edn"]

[formatter.just]
command = "just"
options = ["--unstable", "--fmt", "--justfile"]
includes = ["justfile"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.toml]
command = "taplo"
options = ["fmt", "-"]
includes = ["*.toml"]

[formatter.shell]
command = "shfmt"
options = ["-i", "2", "-ci", "-s", "-w"]
includes = ["*.sh", "*.bash"]
