[package]
name = "bits-axum-session-sqlx"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1"
axum_session = "0.17.1"
chrono = "0.4"
serde_json = "1"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
