[application]
name = "bits-solo"
default_platform = "web"

# Disable Dioxus' built-in Tailwind support
tailwind_input = "please-do-not-exist.css"
tailwind_output = "/tmp/bits-solo.css"

[web.app]
title = "Bits"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[web.watcher]
reload_html = true
