[package]
name = "bits-db"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
jiff.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror = "2"
url = "2"
