[package]
name = "bits-e2e"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[features]
default = ["server"]
server = ["bits-solo/server", "bits-colo/server", "bits-app/colo"]

[dependencies]
bits-app.workspace = true
bits-db.workspace = true
bits-solo.workspace = true
bits-colo.workspace = true
anyhow.workspace = true
axum = "0.8"
reqwest = { version = "0.12", features = ["json"] }
sqlx.workspace = true
tokio.workspace = true
uuid = { version = "1", features = ["v4"] }
