# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["james@invetica.co.uk"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-kv-store"
description = "Just kicking the tyres on Rust at the Edge."
language = "rust"
manifest_version = 3
name = "bits"
service_id = ""

[local_server]

[local_server.kv_stores]

[[local_server.kv_stores.my-store]]
key = "readme"

[scripts]
build = "cargo build --profile release --target wasm32-wasip1"

[setup]

[setup.kv_stores]

[setup.kv_stores.my-store]
description = "My first kv store"
